### PR TITLE
Plugin state locations containing paths were not handled properly.

### LINKED ISSUE #7: Plugin doesn't seem to handle paths with spaces properly.
This plugin has been [suggested](https://www.eclipse.org/forums/index.php?t=rview&th=1102129) as a replacement for DLTK, but after installing and restarting Eclipse errors like the following get logged when it tries to install itself:

    Unexpected exit value 1 from command [cmd.exe, /c, gem install -V -n C:\Users\tschoening\Documents\Eclipse\Ruby GitHub\.metadata\.plugins\io.github.pyvesb.eclipse_solargraph solargraph]
Error details:
ERROR:  Could not find a valid gem 'GitHub\.metadata\.plugins\io.github.pyvesb.eclipse_solargraph' (>= 0) in any repository

The problem most likely is that the path containing spaces is not quoted properly. The following executed manually on the shell succeeds:

    cmd.exe /c gem install -V -n "C:\Users\tschoening\Documents\Eclipse\Ruby GitHub\.metadata\.plugins\io.github.pyvesb.eclipse_solargraph" solargraph

[Source line](https://github.com/PyvesB/eclipse-solargraph/blob/master/eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java#L32):

    String[] command = CommandHelper
				.getPlatformCommand("gem install -V " + "-n " + pluginStateLocation + " " + gem.toLowerCase());

### PR DESCRIPTION
**Pull request by ams-tschoening**
Therefore extracted things into an individual function and added quoting.

> cmd.exe /c gem install -V -n "[...]" "solargraph"
> cmd.exe /c gem update -V -n "[...]" "solargraph"

This fixes #7.

### CODE REVIEW

File: eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java [hunk 1]
```diff
@@ -26,11 +26,17 @@
 
 public class GemHelper {
 
+	private static String buildPlatformCmd(String cmd, String gem) {
```
Comment (PyvesB) [inline eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java]: Would naming this method as `buildGemCmd` be more appropriate? There is nothing platform-specific about it.

File: eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java [hunk 2]
```diff
@@ -26,11 +26,17 @@
...
+		return String.format(
+			"gem %s -V -n \"%s\" \"%s\"",
```
Comment (PyvesB) [inline eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java]: Is there any benefit to quoting the gem name?

**Review by PyvesB — COMMENTED** [review]
Thanks for this! A couple of small observations.

File: eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java (hunk 1 above)
Comment (ams-tschoening) [reply eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java]: If you prefer so... Just named it the way it is because `getPlatformCommand` was around already and `buildCmd` read a bit too short and unspecific.

File: eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java (hunk 2 above)
Comment (ams-tschoening) [reply eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java]: I just wanted to make sure, it was easy to add and it shouldn't harm. Don't know if GEM names with spaces are even possible, though. Remove or leave it?

Comment (PyvesB) [reply eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java]: I don't _think_ it's possible even though the [naming conventions](https://guides.rubygems.org/name-your-gem/) don't seem to explicitly mention any constraints against spaces. Given the only two options at the moment are `solargraph` and `readapt`, I suggest removing them. 😄

**Review by PyvesB — APPROVED** [review]
All good, thanks! 👍
